server:
  port: 3000
spring:
  profiles:
    include: db, app, mybatis, auth, logging, undertow, redis
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

proxy:
  host: 192.168.1.7
  port: 7890